# Generated by Django 2.2 on 2019-09-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Blog',
        ),
    ]
