# Generated by Django 2.2.4 on 2019-09-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190902_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='PostList',
        ),
        migrations.DeleteModel(
            name='SignIn',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
