# Generated by Django 2.2.4 on 2019-09-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190904_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_summary',
        ),
    ]
